<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.avaje</groupId>
    <artifactId>avaje-jex-parent</artifactId>
    <version>3.3-RC4</version>
  </parent>

  <groupId>com.avaje</groupId>
  <artifactId>avaje-jex-realworld</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.release>24</maven.compiler.release>
    <maven.compiler.proc>full</maven.compiler.proc>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <graalvm.version>24.0.2</graalvm.version>

    <avaje.validator.version>2.12</avaje.validator.version>
  </properties>

  <dependencies>

    <dependency>
      <groupId>com.google.flatbuffers</groupId>
      <artifactId>flatbuffers-java</artifactId>
      <version>25.2.10</version>
    </dependency>

    <dependency>
      <groupId>com.auth0</groupId>
      <artifactId>java-jwt</artifactId>
      <version>4.5.0</version>
    </dependency>

    <dependency>
      <groupId>io.ebean</groupId>
      <artifactId>ebean-postgres</artifactId>
    </dependency>

    <dependency>
      <groupId>io.jstach.rainbowgum</groupId>
      <artifactId>rainbowgum-slf4j</artifactId>
      <version>0.8.2</version>
    </dependency>

    <dependency>
      <groupId>dev.mccue</groupId>
      <artifactId>jdbc</artifactId>
      <version>2025.05.29</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.13.4</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.github.slugify</groupId>
      <artifactId>slugify</artifactId>
      <version>3.0.7</version>
    </dependency>

    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.7.7</version>
    </dependency>

    <dependency>
      <groupId>org.lmdbjava</groupId>
      <artifactId>lmdbjava</artifactId>
      <version>0.9.1</version>
    </dependency>
    <dependency>
      <groupId>com.github.chrisvest</groupId>
      <artifactId>stormpot</artifactId>
      <version>4.1</version>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-config</artifactId>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-jex</artifactId>
    </dependency>
    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-jex-static-content</artifactId>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-http-api</artifactId>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-inject</artifactId>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-jsonb</artifactId>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-validator</artifactId>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-validator-constraints</artifactId>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-inject-test</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Annotation processors-->
    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-inject-generator</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-http-jex-generator</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-jsonb-generator</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.avaje</groupId>
      <artifactId>avaje-validator-generator</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.ebean</groupId>
      <artifactId>querybean-generator</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.38</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.38</version>
            </path>
            <path>
              <groupId>io.avaje</groupId>
              <artifactId>avaje-jsonb-generator</artifactId>
            </path>
              <path>
                  <groupId>io.avaje</groupId>
                  <artifactId>avaje-validator-generator</artifactId>
              </path>
            <path>
              <groupId>io.avaje</groupId>
              <artifactId>avaje-inject-generator</artifactId>
            </path>
            <path>
              <groupId>io.ebean</groupId>
              <artifactId>querybean-generator</artifactId>
            </path>
            <path>
              <groupId>io.avaje</groupId>
              <artifactId>avaje-http-jex-generator</artifactId>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>

	  <!-- Create Modular Jar and copy dependencies -->
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-modules</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/modules</outputDirectory>
              <includeScope>runtime</includeScope>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <outputDirectory>${project.build.directory}/modules</outputDirectory>
          <archive>
            <manifest>
              <mainClass>com.avaje.jdk.realworld.AvajeRealWorldApplication</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>

      <plugin>
        <groupId>io.ebean</groupId>
        <artifactId>ebean-maven-plugin</artifactId>
        <extensions>true</extensions>
        <executions>
          <execution>
            <phase>process-classes</phase>
            <configuration>
              <packages>com.avaje.jdk.realworld.**</packages>
              <transformArgs>debug=1</transformArgs>
            </configuration>
            <goals>
              <goal>enhance</goal>
              <goal>testEnhance</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Adds META-INF/services entries to module-info -->
      <plugin>
          <groupId>io.avaje</groupId>
          <artifactId>avaje-provides-maven-plugin</artifactId>
          <executions>
            <execution>
              <goals>
                <goal>disable-apt-validation</goal>
                <goal>add-module-spi</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>native</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>0.10.2</version>
            <extensions>true</extensions>
            <executions>
              <execution>
                <id>build-native</id>
                <goals>
                  <goal>compile-no-fork</goal>
                </goals>
                <phase>package</phase>
              </execution>
            </executions>
            <configuration>
              <verbose>true</verbose>
              <mainClass>com.avaje.jdk.realworld.AvajeRealWorldApplication</mainClass>
              <buildArgs>
                <buildArg>--emit build-report</buildArg>
                <buildArg>--no-fallback</buildArg>
                <buildArg>--enable-sbom</buildArg>
                <buildArg>--enable-url-protocols=http,https</buildArg>
                <buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
                <buildArg>-H:Log=registerResource:3</buildArg>
                <buildArg>-H:IncludeResources=".*.sql|.*.html|.*.css|.*.js|.*.ico|.*.png"</buildArg>
              </buildArgs>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>native_cfg</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>0.10.2</version>
            <extensions>true</extensions>
            <executions>
              <execution>
                <id>build-native</id>
                <goals>
                  <goal>compile-no-fork</goal>
                </goals>
                <phase>package</phase>
              </execution>
            </executions>
            <configuration>
              <verbose>true</verbose>
              <mainClass>com.avaje.jdk.realworld.AvajeRealWorldApplication</mainClass>
              <buildArgs>
                <buildArg>--emit build-report</buildArg>
                <buildArg>--no-fallback</buildArg>
                <buildArg>--enable-sbom</buildArg>
                <buildArg>--enable-url-protocols=http,https</buildArg>
                <buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
                <buildArg>-H:ConfigurationFileDirectories=./</buildArg>
                <buildArg>-H:Log=registerResource:3</buildArg>
                <buildArg>-H:IncludeResources=".*.sql|.*.html|.*.css|.*.js|.*.ico|.*.png"</buildArg>
              </buildArgs>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    </profiles>
</project>